my:
  appId: 123

server:
  port: 80

  # 在响应头中添加返回数据所使用的字符集
  # `Content-Type: application/json;charset=UTF-8`
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            # 顺序相关
            - PrePostHeader=developer,xuxianjie-auth
            - name: CircuitBreaker
              args:
                name: authFallback
                fallbackUri: forward:/fallback/auth?appId=${my.appId}
        - id: authFallback
          uri: http://localhost
          predicates:
            - Path=/fallback/auth
            - Query=appId,${my.appId}
          filters:
            - RewritePath=/fallback/auth,/fallback

        - id: es
          uri: http://localhost:8081
          predicates:
            - Path=/es/**
          filters:
            - RewritePath=/es/(?<path>.*),/$\{path}
            # 顺序相关
            - name: RequestRateLimiter
              # 1 QPS
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                redis-rate-limiter.requestedTokens: 1
            - TokenCheck
            - PrePostHeader=developer,xuxianjie-es
            - name: CircuitBreaker
              args:
                name: esFallback
                fallbackUri: forward:/fallback/news?appId=${my.appId}
        - id: esFallback
          uri: http://localhost:8082
          predicates:
            - Path=/fallback/news
            - Query=appId,${my.appId}
          filters:
            - RewritePath=/fallback/news,/gw/news

logging:
  level:
    org.springframework.cloud.gateway: warn
